version: '3.8'

services:
  warehouse-bot:
    build: .
    container_name: warehouse-automation
    restart: unless-stopped
    environment:
      # KeyCRM интеграция
      - KEYCRM_API_TOKEN=${KEYCRM_API_TOKEN}
      - KEYCRM_WEBHOOK_SECRET=${KEYCRM_WEBHOOK_SECRET}
      
      # Google Sheets
      - GSHEETS_ID=${GSHEETS_ID}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      
      # Telegram
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
      - TELEGRAM_ADMIN_USERS=${TELEGRAM_ADMIN_USERS}
      
      # Webhook endpoint
      - WEBHOOK_ENDPOINT=${WEBHOOK_ENDPOINT}
      
      # Параметры планирования
      - LEAD_TIME_DAYS=${LEAD_TIME_DAYS:-14}
      - SCRAP_PCT=${SCRAP_PCT:-0.05}
      - TARGET_COVER_DAYS=${TARGET_COVER_DAYS:-14}
      - MIN_STOCK_DEFAULT=${MIN_STOCK_DEFAULT:-100}
      - PAR_STOCK_DEFAULT=${PAR_STOCK_DEFAULT:-300}
      
      # Технические параметры
      - TIMEZONE=${TIMEZONE:-Europe/Kyiv}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    
    networks:
      - warehouse-network
    
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  warehouse-network:
    driver: bridge