version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timosh-blanks-webhook-dev
    command: uvicorn src.webhook.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
      - ./logs:/app/logs
    restart: "no"
    networks:
      - timosh-network

  # Для разработки не запускаем scheduler и bot автоматически
  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: timosh-blanks-scheduler-dev
  #   command: python -m src.scheduler.runner
  #   env_file:
  #     - .env
  #   environment:
  #     - DEBUG=true
  #   volumes:
  #     - ./src:/app/src
  #     - ./data:/app/data
  #     - ./logs:/app/logs
  #   restart: "no"
  #   networks:
  #     - timosh-network

  redis:
    image: redis:7-alpine
    container_name: timosh-blanks-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: "no"
    networks:
      - timosh-network

volumes:
  redis_dev_data:
    driver: local

networks:
  timosh-network:
    driver: bridge